### ISSUE TITLE
Example script - Failed with onlineshop

### ISSUE THREAD

**Issue by minthemiddle** [skroutz/wappalyzer-ruby#4]
I tried to use the [example script](https://github.com/skroutz/wappalyzer-ruby/blob/master/examples/analyze_example.rb) on a Ubuntu 13.04 machine with the following command:

```
ruby example_script.rb 'www.geigenmarkt.com'
```

And got this error message:

```
/var/lib/gems/1.9.1/gems/wappalyzer_rb-0.0.6/lib/wappalyzer_rb.rb:19:in `get': undefined method `request_uri' for #<URI::Generic:0x00000001a7aea8 URL:www.geigenmarkt.com> (NoMethodError)
    from /var/lib/gems/1.9.1/gems/wappalyzer_rb-0.0.6/lib/wappalyzer_rb.rb:62:in `response'
    from /var/lib/gems/1.9.1/gems/wappalyzer_rb-0.0.6/lib/wappalyzer_rb.rb:30:in `data'
    from /var/lib/gems/1.9.1/gems/wappalyzer_rb-0.0.6/lib/wappalyzer_rb.rb:90:in `block (2 levels) in analyze!'
    from /var/lib/gems/1.9.1/gems/wappalyzer_rb-0.0.6/lib/wappalyzer_rb.rb:83:in `each'
    from /var/lib/gems/1.9.1/gems/wappalyzer_rb-0.0.6/lib/wappalyzer_rb.rb:83:in `block in analyze!'
    from /var/lib/gems/1.9.1/gems/wappalyzer_rb-0.0.6/lib/wappalyzer_rb.rb:82:in `each'
    from /var/lib/gems/1.9.1/gems/wappalyzer_rb-0.0.6/lib/wappalyzer_rb.rb:82:in `analyze!'
    from /var/lib/gems/1.9.1/gems/wappalyzer_rb-0.0.6/lib/wappalyzer_rb.rb:13:in `initialize'
    from wapp.rb:7:in `new'
    from wapp.rb:7:in `<main>'
```

Versions of all used software:

```
ruby1.8, 1.8.7.358-7ubuntu1.1
rubygems 1.8.24-1ubuntu1
wappalyzer_rb-0.0.6

What did I do wrong? Does it not work with onlineshops yet? 
```

**Comment by juliangutierrez** [comment]
Probably too late, but you should put the 'http://'
